print("What is your name human?")
name = input()
print("\nHow old are you (in years)?")
age = int(input())
print("\nHow tall are you (in meters)?")
high = float(input())
print("\nHow much do you weigh (in kilograms)?")
kg = int(input())
print(f"\n{name} you are {age} years old and your bmi is { kg / high ** 2:.2f}.")
